//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÜrünYönetimSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaSayfas
    {
        public int id { get; set; }
        public string unvan { get; set; }
        public string isim { get; set; }
    }
}
