//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÜrünYönetimSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNIMAGE
    {
        public int URUNIMAGEID { get; set; }
        public string IMAGEAD { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public Nullable<int> URUNID { get; set; }
    
        public virtual TBLURUNLER TBLURUNLER { get; set; }
        public virtual TBLURUNOZELLIKLERI TBLURUNOZELLIKLERI { get; set; }
    }
}
